apiVersion: kubernetes.mckesson.com/v1alpha1
kind: AksClusterClaim
metadata:
  name: aks-demo-cluster
  annotations:
    crossplane.io/external-name: aks-demo-cluster  
spec:
  writeConnectionSecretToRef:
    name: aks-demo-cluster-secret
  location: "EastUs"
  aks:
    adminUser: #<<Insert Here: Object Id of the User>>
    tags:
      environment: demo
      "core-snow-as-number": "123456789"
  virtualNetwork:
    tags:
      environment: demo 