# Production environment specific cert-manager configuration

# Controller configuration for production
controller:
  # High resource allocation for production
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  
  # Multiple replicas for high availability
  replicaCount: 3
  
  # Pod disruption budget for production
  podDisruptionBudget:
    enabled: true
    minAvailable: 2

# Webhook configuration for production
webhook:
  # High resource allocation for production
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  
  # Pod disruption budget for production
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

# CA Injector configuration for production
cainjector:
  # High resource allocation for production
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  
  # Pod disruption budget for production
  podDisruptionBudget:
    enabled: true
    minAvailable: 1 