# Production environment specific ArgoCD configuration with ingress

server:
  # Ingress configuration for production ArgoCD
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      # ArgoCD specific annotations
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Frame-Options DENY";
        more_set_headers "X-Content-Type-Options nosniff";
        more_set_headers "X-XSS-Protection 1; mode=block";
      # Production specific annotations
      nginx.ingress.kubernetes.io/rate-limit: "200"
      nginx.ingress.kubernetes.io/rate-limit-window: "1m"
      # Additional security headers for production
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Frame-Options DENY";
        more_set_headers "X-Content-Type-Options nosniff";
        more_set_headers "X-XSS-Protection 1; mode=block";
        more_set_headers "Strict-Transport-Security max-age=31536000; includeSubDomains";
        more_set_headers "Content-Security-Policy default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';";
    hosts:
      - host: argocd.poc-prod.westus3.mckesson.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.poc-prod.westus3.mckesson.com

  # Service configuration for production
  service:
    type: ClusterIP
    annotations:
      prometheus.io/scrape: true 