controller:
  # High resource allocation for production
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  
  # Multiple replicas for high availability
  replicaCount: 3
  
  # Autoscaling configuration for production
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 15
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 60
  
  # Service configuration for production
  service:
    type: LoadBalancer
    annotations:
      # Azure Load Balancer annotations for production
      service.beta.kubernetes.io/azure-load-balancer-internal: false
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: ""
      service.beta.kubernetes.io/azure-load-balancer-sku: "Standard"
      # Additional annotations for production
      service.beta.kubernetes.io/azure-load-balancer-name: "prod-ingress"
      # Enable session affinity for production
      service.beta.kubernetes.io/azure-load-balancer-session-affinity: "ClientIP"
  
  # Pod disruption budget for production
  podDisruptionBudget:
    enabled: true
    minAvailable: 2
  
  # Performance tuning for production
  config:
    # Enable proxy protocol for Azure Load Balancer
    use-proxy-protocol: "false"
    # Configure real IP from Azure Load Balancer
    use-forwarded-headers: "true"
    # Enable real client IP
    real-ip-header: "X-Forwarded-For"
    # Trusted proxies (Azure Load Balancer IPs)
    proxy-real-ip-cidr: "0.0.0.0/0"
    # Performance tuning
    worker-processes: "auto"
    worker-connections: "1024"
    keep-alive-requests: "10000"
    keep-alive: "on"
    # Buffer sizes for high traffic
    proxy-buffer-size: "16k"
    proxy-buffers-number: "8"
    proxy-buffering: "on"

# Default backend configuration for production
defaultBackend:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi 