provider:
  enabled: true
  metadata:
    annotations: {}
    labels:
      app.kubernetes.io/managed-by: Helm
      azure.workload.identity/use: "true"
  package:
    registry: xpkg.upbound.io/upbound
    version: v1.13.1

deploymentRuntimeConfig:
  enabled: true
  env:
    - name: AZURE_API_VERSION
      value: "2024-11-01"
    - name: TF_VAR_azure_api_version
      value: "2024-11-01"
    - name: TF_VAR_azurerm_api_version
      value: "2024-11-01"

# Provider configuration
providerConfig:
  enabled: true
  apiVersion: "2024-11-01"
