
apiVersion: kubernetes.mckesson.com/v1alpha1
kind: AksClusterClaim
metadata:
  name: aks-ce-eastus-dev
  annotations:
    crossplane.io/external-name: aks-ce-eastus-dev  
spec:
  writeConnectionSecretToRef:
    name: aks-ce-eastus-dev-secret
  location: "EastUs"
  aks:
    adminUser: "35f987a7-2b25-4603-82f9-7db52032afdf"
    tags:
      environment: dev
      "core-snow-as-number": "123456789"
  virtualNetwork:
    tags:
      environment: dev   
