
apiVersion: kubernetes.example.com/v1alpha1
kind: AksClusterClaim
metadata:
  name: aks-ce-eastus-dev
  annotations:
    crossplane.io/external-name: aks-ce-eastus-dev  
spec:
  writeConnectionSecretToRef:
    name: aks-ce-eastus-dev-secret
  location: "EastUs"
  aks:
    adminUser: #<<Insert Here: Object Id of the User>>
    tags:
      environment: dev
      "core-snow-as-number": "123456789"
  virtualNetwork:
    tags:
      environment: dev   
