namespace: aks-ce-eastus-dev

resources:
  - ../base
  - namespace.yaml

patches:
- path: cluster-claim.yaml 
  target:
    group: kubernetes.mckesson.com
    version: v1alpha1
    kind: AksClusterClaim
    name: aks-ce-eastus-dev
- patch: |-
    - op: replace
      path: /metadata/name
      value: aks-ce-eastus-dev  
  target:
    kind: AksClusterClaim
- patch: |-
    - op: add
      path: /spec/aks/adminUser
      value: "35f987a7-2b25-4603-82f9-7db52032afdf"
  target:
    kind: AksClusterClaim     