# Dev environment specific ArgoCD configuration with ingress

server:
  # Ingress configuration for dev ArgoCD
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      # ArgoCD specific annotations
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Frame-Options DENY";
        more_set_headers "X-Content-Type-Options nosniff";
        more_set_headers "X-XSS-Protection 1; mode=block";
      # Dev environment specific annotations
      nginx.ingress.kubernetes.io/rate-limit: "50"
      nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    hosts:
      - host: argocd.poc-dev.westus3.mckesson.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.poc-dev.westus3.mckesson.com

  # Service configuration for dev
  service:
    type: ClusterIP
    annotations:
      prometheus.io/scrape: true 