apiVersion: kubernetes.mckesson.com/v1alpha1
kind: AksClusterClaim
metadata:
  name: aks-test-fix
  annotations:
    crossplane.io/external-name: aks-test-fix  
spec:
  writeConnectionSecretToRef:
    name: aks-test-fix-secret
  location: "WestUS3"
  aks:
    defaultNodePool:
      name: "system"
      vmSize: Standard_B2s
      enableAutoScaling: true
      nodeCount: 1
      minCount: 1
      maxCount: 2
      maxPods: 50
      nodeLabels:
        mode: system
      onlyCriticalAddonsEnabled: false
      osDiskSizeGb: 128
      osDiskType: Managed
    networkProfile:
      - networkPlugin: "azure"
        networkPolicy: azure
        outboundType: loadBalancer
        dnsServiceIp: 10.300.0.10
        serviceCidr: 10.300.0.0/16
    tags:
      environment: test
      "core-snow-as-number": "123456789"
  userNodePool:
    name: user
    vmSize: Standard_B2s
    enableAutoScaling: true
    nodeCount: 1
    minCount: 1
    maxCount: 2
    maxPods: 50
    nodeLabels:
      mode: user
    osDiskSizeGb: 128
    osDiskType: Managed
    osSku: AzureLinux
    osType: Linux
  virtualNetwork:
    addressSpace: ["10.300.0.0/16"]
    tags:
      environment: test
      provisionedBy: Crossplane
  subnet:
    name: "subnet-aks-test-fix"
    addressPrefixes: ["10.300.0.0/24"]
    privateEndpointNetworkPoliciesEnabled: true
    privateLinkServiceNetworkPoliciesEnabled: false 